image:
  name: hashicorp/terraform:light
  entrypoint:
  - '/usr/bin/env'
  - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

variables:
  PLANFILE: planfile

before_script:
- terraform -version

stages:
- Initialization
- Integration Tests
- Plan Deployment
- Apply Changes

init:
  stage: Initialization
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - .terraform/
  script:
  - |
    terraform init -input=false \
    -backend-config="bucket=$BACKEND_BUCKET" \
    -backend-config="dynamodb_table=$BACKEND_TABLE" \
    -backend-config="region=$BACKEND_REGION"
  - terraform get -update=true

validate:
  stage: Integration Tests
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
    paths:
    - .terraform/
  script:
  - terraform validate

plan:
  stage: Plan Deployment
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
    paths:
    - .terraform/
  script:
  - terraform plan -input=false -out=$PLANFILE
  artifacts:
    name: planfile
    expire_in: 1 day
    paths:
    - $PLANFILE

apply:
  stage: Apply Changes
  dependencies:
  - plan
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
    paths:
    - .terraform/
  script:
  - terraform apply -input=false $PLANFILE
  only:
    refs:
    - master
