image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

variables:
  PLANFILE: planfile

cache:
  paths:
  - .terraform

before_script:
- rm -rf .terraform
- terraform -version
- terraform init -backend-config="bucket=$BACKEND_BUCKET" -backend-config="dynamodb_table=$BACKEND_TABLE" -backend-config="region=$BACKEND_REGION"

stages:
- validate
- plan
- apply

validate:
  stage: validate
  script:
  - terraform validate

plan:
  stage: plan
  script:
  - terraform plan -out=$PLANFILE
  dependencies:
    - validate
  artifacts:
    name: planfile
    paths:
    - $PLANFILE

apply:
  stage: apply
  script:
  - terraform apply -input=false $PLANFILE
  environment:
    name: production
  dependencies:
    - plan
  when: manual
  only:
  - master
