image:
  name: hashicorp/terraform:light
  entrypoint:
  - '/usr/bin/env'
  - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

variables:
  PLANFILE: planfile

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - .terraform/

before_script:
- terraform -version

stages:
- Initialization
- Integration Tests
- Plan Deployment
- Apply Changes

terraform init:
  stage: Initialization
  script:
  - |
    terraform init -input=false \
    -backend-config="bucket=$BACKEND_BUCKET" \
    -backend-config="dynamodb_table=$BACKEND_TABLE" \
    -backend-config="region=$BACKEND_REGION"

terraform get:
  stage: Initialization
  script:
  - terraform get -update=true

terraform validate:
  stage: Integration Tests
  script:
  - terraform validate

terraform plan:
  stage: Plan Deployment
  script:
  - terraform plan -input=false -out=$PLANFILE
  artifacts:
    name: planfile
    expire_in: 1 day
    paths:
    - $PLANFILE

terraform apply:
  stage: Apply Changes
  script:
  - terraform apply -input=false $PLANFILE
  dependencies:
  - terraform plan
  only:
    refs:
    - master
